PUSHD %~dp0
set "currdir=%cd%"

mklink /d "%currdir%\addons\SimpleAssetManager" "%currdir%\GIT\simple-asset-manager\SimpleAssetManager" 
mklink /d "%currdir%\addons\fspy" "%currdir%\GIT\fSpy-Blender\fspy_blender"
mklink /d "%currdir%\addons\mesh_mesh_align_plus" "%currdir%\GIT\mesh_align_plus\mesh_mesh_align_plus"
mklink /d "%currdir%\addons\screencastkeys" "%currdir%\GIT\ScreenCast-Keys\src\screencastkeys"
mklink /d "%currdir%\addons\mira_tools" "%currdir%\GIT\mifthtools\blender\addons\2.8\mira_tools"
mklink /d "%currdir%\addons\PolyQuilt" "%currdir%\GIT\PolyQuilt\Addons\PolyQuilt"
mklink /d "%currdir%\addons\vertex_color_master" "%currdir%\GIT\vertex_color_master\vertex_color_master"
mklink /d "%currdir%\addons\MathsExpressionLiteBlender" "%currdir%\GIT\Blender-Addons\MathsExpressionLiteBlender28"
mklink /d "%currdir%\addons\MapsModelsImporter" "%currdir%\GIT\MapsModelsImporter\blender\MapsModelsImporter"
mklink /d "%currdir%\addons\Polycount" "%currdir%\GIT\Polycount\polycount"
mklink /d "%currdir%\addons\Texel_Density" "%currdir%\GIT\Texel-Density-Checker\Texel_Density_3_1_281"
mklink /d "%currdir%\addons\uv-packer" "%currdir%\GIT\uvpacker\uv-packer"
mklink /d "%currdir%\addons\uvpacker_exe" "%currdir%\GIT\uvpacker_exe"
@REM mklink /d "%currdir%\addons\io_mesh_fast_obj" "%currdir%\GIT\bpy_photogrametry\io_mesh_fast_obj"
mklink /d "%currdir%\addons\math_formula" "%currdir%\GIT\WM_Blender-addons\math_formula"
mklink /d "%currdir%\addons\photogrammetry_importer" "%currdir%\GIT\Blender-Addon-Photogrammetry-Importer\photogrammetry_importer"

"%PYTHONPATH%\python.exe" "..\GIT\BEER\Malt\scripts\package_blender_addon.py"
mklink /d "%currdir%\addons\BlenderMalt" "%currdir%\GIT\BEER\Malt\BlenderMalt"
mklink /d "%currdir%\addons\BlenderMalt\MaltPath\Malt" "%currdir%\GIT\BEER\Malt\Malt"

mklink /d "%currdir%\addons\hairNet" "%currdir%\GIT\HairNet\hairNet"
powershell -Command "(gc addons\hairNet\hairNet.py) -replace 'DEBUG = 1', 'DEBUG = 0' | Out-File -encoding ASCII addons\hairNet\hairNet.py"

mklink /h "%currdir%\presets\interface_theme\blender_pro.xml" "%currdir%\GIT\ProTheme\blender_pro.xml"
mklink /h "%currdir%\addons\RenderBurst.py" "%currdir%\GIT\RenderBurst\RenderBurst.py"
mklink /h "%currdir%\addons\Object_Shake.py" "%currdir%\GIT\object-shake\Object_Shake.py"
mklink /h "%currdir%\addons\TiNA.py" "%currdir%\GIT\TiNA\TiNA.py"
mklink /h "%currdir%\addons\blenderbezierutils.py" "%currdir%\GIT\bezierutils\blenderbezierutils.py"
mklink /h "%currdir%\addons\Lodify.py" "%currdir%\GIT\Lodify\Lodify.py"
mklink /h "%currdir%\addons\carbon_tools.py" "%currdir%\GIT\bpy_photogrametry\carbon_tools.py"
mklink /h "%currdir%\addons\io_import_photoscan_cameras.py" "%currdir%\GIT\bpy_photogrametry\io_import_photoscan_cameras.py"
mklink /h "%currdir%\addons\system_time_tracker.py" "%currdir%\GIT\bpy_photogrametry\system_time_tracker.py"
mklink /h "%currdir%\addons\space_view3d_point_cloud_visualizer.py" "%currdir%\GIT\bpy_photogrametry\space_view3d_point_cloud_visualizer.py"
mklink /h "%currdir%\addons\advanced_transform.py" "%currdir%\GIT\advanced_transform\advanced_transform_2_8.py"
mklink /h "%currdir%\addons\Asset_Creation_Toolset.py" "%currdir%\GIT\Asset-Creation-Toolset\Asset_Creation_Toolset_2_6_1_281.py"
mklink /h "%currdir%\addons\oscurart_edit_split_normals.py" "%currdir%\GIT\oscuart\oscurart_edit_split_normals.py"
mklink /h "%currdir%\addons\oscurart_bake_pbr.py" "%currdir%\GIT\oscuart\oscurart_bake_pbr.py"
mklink /h "%currdir%\addons\object_convert_to_armature.py" "%currdir%\GIT\Export-Paper-Model\object_convert_to_armature.py"
mklink /h "%currdir%\addons\optiloops.py" "%currdir%\GIT\optiloops\optiloops_v1_2_0.py"

mklink /h "%currdir%\startup\HEAVYPOLY_OPERATORS.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_OPERATORS.py"
mklink /h "%currdir%\startup\HEAVYPOLY_pie_rotate_90.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_pie_rotate_90.py"
mklink /h "%currdir%\startup\HEAVYPOLY_pie_areas.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_pie_areas.py"
mklink /h "%currdir%\startup\HEAVYPOLY_pie_symmetry.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_pie_symmetry.py"
mklink /h "%currdir%\startup\HEAVYPOLY_pie_add.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_pie_add.py"
mklink /h "%currdir%\startup\HEAVYPOLY_pie_boolean.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_pie_boolean.py"
mklink /h "%currdir%\startup\HEAVYPOLY_select_through_border.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\HEAVYPOLY_select_through_border.py"
mklink /h "%currdir%\startup\jmQuickPipe.py" "%currdir%\GIT\HEAVYPOLY\scripts\startup\jmQuickPipe.py"

pause
